import React, { useState } from 'react';
import { MovieProject } from '../types';
import { generateBlackAndWhitePdf } from '../services/pdfGenerator';
import { X, FileDown, Check, Printer, Sparkles, Film, Copy, FileText, CheckCircle2 } from 'lucide-react';
import confetti from 'canvas-confetti';

interface PdfExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  project: MovieProject;
}

export const PdfExportModal: React.FC<PdfExportModalProps> = ({
  isOpen,
  onClose,
  project,
}) => {
  const [copied, setCopied] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [pdfDownloaded, setPdfDownloaded] = useState(false);

  if (!isOpen) return null;

  const handleDownloadBwPdf = () => {
    setIsGeneratingPdf(true);
    setPdfDownloaded(false);

    try {
      generateBlackAndWhitePdf(project);
      
      confetti({
        particleCount: 65,
        spread: 60,
        origin: { y: 0.6 },
        colors: ['#C6A24D', '#E8C878', '#FFF2CC'],
      });

      setPdfDownloaded(true);
      setTimeout(() => setPdfDownloaded(false), 3000);
    } catch (err) {
      console.error('Failed to generate B&W PDF:', err);
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleTriggerPrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    const md = `# ${project.title} — Overall Production Intelligence Report
*${project.tagline}*
**Target Industry:** ${project.targetIndustry} | **Genre:** ${project.genre} | **Est. Budget:** ${project.estimatedBudgetRange}

---

## 1. Executive Story Analysis
**Logline:** ${project.storyAnalysis.logline}
**Synopsis:** ${project.storyAnalysis.synopsis}
**Themes:** ${project.storyAnalysis.themes.join(', ')}
**Tone & Structure:** ${project.storyAnalysis.emotionalTone} — ${project.storyAnalysis.pacing}
**Target Audience & Market:** ${project.storyAnalysis.targetAudience} — ${project.storyAnalysis.marketPotential}

---

## 2. Character Intelligence Dossiers & Casting Roster
${project.characters.map((c, i) => `
### 2.${i + 1} ${c.name} (${c.role} — Age ${c.ageRange})
- **Archetype:** ${c.archetype}
- **Motivation:** ${c.motivation}
- **Casting Specifications:** ${c.castingRequirements}
- **Dramatic Arc:** ${c.characterJourney}
- **Ranked Casting Matches:**
${c.recommendations.map(r => `  ${r.rank}. **${r.name}** (${r.matchPercentage}% match — ${r.experienceLevel} | Budget: ${r.budgetImpact})\n     *Reasoning:* ${r.reasoning}\n     *Rubric:* Acting Style ${r.rubric.actingStyleMatch}/25, Age ${r.rubric.ageAppearance}/15, Genre ${r.rubric.genreExperience}/15, Range ${r.rubric.emotionalRange}/15, Roles ${r.rubric.previousRoleSimilarity}/15, Presence ${r.rubric.screenPresence}/10`).join('\n')}
`).join('\n')}

---

## 3. Character Relationships Network
${project.relationships.map((r, i) => `
### 3.${i + 1} Tie: ${r.relationType} (${r.emotionalTension} Tension)
- **Arc Summary:** ${r.arcSummary}
- **Turning Point:** "${r.keyTurningPoint}"
`).join('\n')}

---

## 4. Budget Intelligence & Capital Allocation
**Total Estimated Scale:** $${(project.budget.totalEstimatedBudgetUsd / 1000000).toFixed(2)}M USD (${project.budget.scaleBadge} Scale)
${project.budget.complexityParagraph}

**Department Allocations:**
${project.budget.items.map(b => `- **${b.category}:** ${b.percentage}% (~$${(b.estimatedAmountUsd / 1000).toLocaleString()}k USD) [${b.scaleLevel} Intensity] — ${b.description}`).join('\n')}

---

## 5. Locations & Spatial Scouting Matrix
${project.locations.map(l => `- **${l.name}** (${l.type} — ${l.sceneCount} Scenes, ${l.estimatedDays} Days, Permit: ${l.permitComplexity})\n  *Setting:* ${l.setting}\n  *Alternatives:* ${l.realWorldAlternatives.join(', ')}`).join('\n')}

---

## 6. Production Timeline & High-Cost Flags
**Total Duration:** ${project.timeline.totalWeeks} Weeks (Complexity Score: ${project.timeline.complexityScore}/100 — ${project.timeline.complexityBadge})
${project.timeline.phases.map(p => `### ${p.phase} (${p.durationWeeks} Weeks)\n- Milestones: ${p.keyMilestones.join(' • ')}\n- Risks: ${p.criticalRisks.join(' • ')}`).join('\n\n')}

**High-Cost Scene Flags:**
${project.timeline.highCostFlags.map(f => `- **${f.sceneDescription}** (${f.reason} - ${f.costImpact} Risk)\n  *Mitigation:* ${f.mitigationSuggestion}`).join('\n')}

---

## 7. Autonomous AI Production Observations
${project.aiInsights.map((ins, i) => `${i + 1}. ${ins}`).join('\n')}

---

*Generated by CineVerse AI — Production Intelligence Platform.*
`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
      <div className="relative w-full max-w-2xl bg-[#141416] border border-[#C6A24D]/50 rounded-sm shadow-[0_0_50px_rgba(0,0,0,0.9)] overflow-hidden flex flex-col">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#302f33] bg-[#1B1B1E]">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded bg-[#C6A24D]/10 text-[#E8C878] border border-[#C6A24D]/30">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-serif text-lg font-bold text-[#F1F0EC]">Export Overall Analysis Document</h3>
              <p className="text-xs text-[#96959c]">{project.title} • Black & White PDF Format</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded text-[#96959c] hover:text-[#F1F0EC] hover:bg-[#202023] transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="p-6 space-y-5 text-xs text-[#F1F0EC]">
          
          {/* Document Specification Box */}
          <div className="p-4 rounded bg-[#1B1B1E] border border-[#232326] space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-[#E8C878] font-serif font-bold text-xs uppercase tracking-wider">
                <Sparkles className="w-4 h-4" /> Comprehensive Black & White PDF Dossier
              </div>
              <span className="px-2 py-0.5 rounded bg-[#0A0A0B] border border-[#302f33] text-[10px] text-[#96959c]">
                A4 Standard • High-Contrast Monochrome
              </span>
            </div>

            <p className="text-xs text-[#96959c] leading-relaxed">
              Generates an 8-section, high-contrast, structured Black & White production report ready for printing, executive pitch review, and distribution:
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px] text-[#F1F0EC]/80 pt-1">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-[#C6A24D] shrink-0" />
                <span>Executive Story Analysis & Pacing</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-[#C6A24D] shrink-0" />
                <span>Character Dossiers & Top 5 Casting Rubrics</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-[#C6A24D] shrink-0" />
                <span>Interpersonal Relationship Network</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-[#C6A24D] shrink-0" />
                <span>Departmental Budget Capital Allocations</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-[#C6A24D] shrink-0" />
                <span>Location Scouting Matrix & Permits</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-[#C6A24D] shrink-0" />
                <span>Timeline Schedule & High-Cost Flags</span>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            
            {/* 1. Download B&W PDF */}
            <button
              onClick={handleDownloadBwPdf}
              disabled={isGeneratingPdf}
              className="btn-gold-sheen p-3 rounded text-xs font-bold flex items-center justify-center gap-2 shadow-gold-glow sm:col-span-1"
            >
              <FileDown className="w-4 h-4" />
              <span>{isGeneratingPdf ? 'Generating PDF...' : pdfDownloaded ? '✓ Downloaded!' : 'Download B&W PDF'}</span>
            </button>

            {/* 2. Print / Save Dialog */}
            <button
              onClick={handleTriggerPrint}
              className="p-3 rounded text-xs font-semibold bg-[#202023] hover:bg-[#2a2a2e] text-[#F1F0EC] border border-[#302f33] hover:border-[#C6A24D]/50 flex items-center justify-center gap-2 transition-all"
            >
              <Printer className="w-4 h-4 text-[#E8C878]" />
              <span>Print Preview</span>
            </button>

            {/* 3. Copy Markdown */}
            <button
              onClick={handleCopyMarkdown}
              className="p-3 rounded text-xs font-semibold bg-[#202023] hover:bg-[#2a2a2e] text-[#F1F0EC] border border-[#302f33] hover:border-[#C6A24D]/50 flex items-center justify-center gap-2 transition-all"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  <span className="text-emerald-400">Copied to Clipboard!</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 text-[#E8C878]" />
                  <span>Copy Plaintext</span>
                </>
              )}
            </button>
          </div>

          <div className="text-[11px] text-[#6d6c72] leading-tight pt-2 border-t border-[#232326]">
            The PDF document is formatted in clean black-and-white typography with borders, tables, running headers, and page numbering suitable for formal production presentations.
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-[#302f33] bg-[#1B1B1E] flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-1.5 text-xs rounded border border-[#302f33] text-[#96959c] hover:text-[#F1F0EC] hover:bg-[#202023] transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
